#                                                     ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Phoenix Tools ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Phoenix Tools ConfigğŸ’»
#                                                     ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ
#ragnarokTools.Give > Ability to give tools
#ragnarokTools.Help > Shows the help menu
#ragnarokTools.Reload > Reload the plugin config files
#ragnarokTools.List > Shows the tool list menu

#â™¢â™¢â™¢â™¢â™¢MultiBlock Pickaxe Itemâ™¢â™¢â™¢â™¢â™¢
#MultiBlockPickaxe Name -> Name of the world edit wand (Please use & for color codes).
MultiBlockPickaxe-Name: '&5&lMultiBlock &d&lPickaxe'

#MultiBlockPickaxe Lore -> Any lore lines you would like on the world edit wand (Please use & for color codes).
MultiBlockPickaxe-Lore:
  - '&2&lMines in a &43x3x1 &2Area'
  - ''
  - '&bCustom Pickaxe'

#â™¢â™¢â™¢â™¢â™¢Spawner Pickaxe Itemâ™¢â™¢â™¢â™¢â™¢
#MultiBlockPickaxe Name -> Name of the world edit wand (Please use & for color codes).
SpawnerPickaxe-Name: '&6&lSpawner &e&lPickaxe'

#MultiBlockPickaxe Lore -> Any lore lines you would like on the world edit wand (Please use & for color codes).
SpawnerPickaxe-Lore:
  - '&a&lCan pickup any spawner'
  - ''
  - '&bCustom Pickaxe'

#â™¢â™¢â™¢â™¢â™¢Molten Pickaxe Itemâ™¢â™¢â™¢â™¢â™¢
#MultiBlockPickaxe Name -> Name of the world edit wand (Please use & for color codes).
MoltenPickaxe-Name: '&4&lMolten &c&lPickaxe'

#MultiBlockPickaxe Lore -> Any lore lines you would like on the world edit wand (Please use & for color codes).
MoltenPickaxe-Lore:
  - '&3&lAutomatically smelts blocks when you break them'
  - ''
  - '&bCustom Pickaxe'

#â™¢â™¢â™¢â™¢â™¢Cobble Gobble Pickaxe Itemâ™¢â™¢â™¢â™¢â™¢
#MultiBlockPickaxe Name -> Name of the world edit wand (Please use & for color codes).
CobblePickaxe-Name: '&7&lCobble Gobble &f&lPickaxe'

#MultiBlockPickaxe Lore -> Any lore lines you would like on the world edit wand (Please use & for color codes).
CobblePickaxe-Lore:
  - '&8&lInstantly mines stone and cobblestone'
  - ''
  - '&4&lCANNOT MINE OTHER BLOCKS'
  - ''
  - '&bCustom Pickaxe'



#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/ePQGvQuzG3
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default config file.