#                                                     ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Phoenix Tools ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Phoenix Tools ConfigğŸ’»
#                                                     ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ
#ragnarokTools.Give > Ability to give tools
#ragnarokTools.Help > Shows the help menu
#ragnarokTools.Reload > Reload the plugin config files
#ragnarokTools.List > Shows the tool list menu

#â™¢â™¢â™¢â™¢â™¢MultiBlock Pickaxe Itemâ™¢â™¢â™¢â™¢â™¢
#MultiBlockPickaxe Name -> Name of the multiblock pickaxe (Please use & for color codes).
MultiBlockPickaxe-Name: '&5&lMultiBlock Pickaxe'

#MultiBlockPickaxe Lore -> Any lore lines you would like on the multiblock pickaxe (Please use & for color codes).
MultiBlockPickaxe-Lore:
  - '&7Mines in a &f3x3x1 &7Area'
  - ''
  - '&bCustom Pickaxe'

#â™¢â™¢â™¢â™¢â™¢Spawner Pickaxe Itemâ™¢â™¢â™¢â™¢â™¢
#Spawner Pickaxe Name -> Name of the spawner pickaxe (Please use & for color codes).
SpawnerPickaxe-Name: '&6&lSpawner Pickaxe'

#Spawner Pickaxe Lore -> Any lore lines you would like on the spawner pickaxe (Please use & for color codes).
SpawnerPickaxe-Lore:
  - '&7Can pickup any spawner'
  - ''
  - '&bCustom Pickaxe'

#â™¢â™¢â™¢â™¢â™¢Molten Pickaxe Itemâ™¢â™¢â™¢â™¢â™¢
#Molten Pickaxe Name -> Name of the molten pickaxe (Please use & for color codes).
MoltenPickaxe-Name: '&4&lMolten Pickaxe'

#Molten Pickaxe Lore -> Any lore lines you would like on the molten pickaxe (Please use & for color codes).
MoltenPickaxe-Lore:
  - '&7Automatically smelts blocks when you break them'
  - ''
  - '&bCustom Pickaxe'

#â™¢â™¢â™¢â™¢â™¢Cobble Gobble Pickaxe Itemâ™¢â™¢â™¢â™¢â™¢
#Cobble Gobble Pickaxe Name -> Name of the cobble gobble pickaxe (Please use & for color codes).
CobblePickaxe-Name: '&7&lCobble Gobble Pickaxe'

#Cobble Gobble Pickaxe Lore -> Any lore lines you would like on the cobble gobble pickaxe (Please use & for color codes).
CobblePickaxe-Lore:
  - '&7Instantly mines stone and cobblestone'
  - ''
  - '&4CANNOT MINE OTHER BLOCKS'
  - ''
  - '&bCustom Pickaxe'

#â™¢â™¢â™¢â™¢â™¢Harvester Hoe Itemâ™¢â™¢â™¢â™¢â™¢
#Harvester Hoe Name -> Name of the harvester hoe (Please use & for color codes).
HarvesterHoe-Name: '&3&lHarvester &d&lHoe'

#Harvester Hoe Lore -> Any lore lines you would like on the harvester hoe (Please use & for color codes).
HarvesterHoe-Lore:
  - '&7Automatically replants any crops mined'
  - ''
  - '&bCustom Hoe'

#Harvester Hoe Crop Types -> Enabled / Disable specific crops.
#The following crops are the on only ones able to be auto replanted (WHEAT, CARROTS, POTATOES, NETHER_WART, BEETROOTS)
CropsToHarvest:
  - "WHEAT"
  - "CARROTS"
  - "POTATOES"
  - "NETHER_WART"
  - "BEETROOTS"

Replant-Particles: true
Replant-Sound: true






#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/ePQGvQuzG3
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default config file.